/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--background)',
        surface: 'var(--surface)',
        'surface-dim': 'var(--surface-dim)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        card: 'var(--card)',
        popover: 'var(--popover)',
        foreground: 'var(--foreground)',
        ink: 'var(--foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        'muted-fg': 'var(--muted-foreground)',
        border: 'var(--border)',
        rule: 'var(--border)',
        outline: 'var(--border)',
        'outline-variant': 'var(--color-outline-variant)',
        'primary-foreground': 'var(--primary-foreground)',
        primary: {
          DEFAULT: 'var(--primary)',
          fg: 'var(--primary-foreground)',
          hover: 'var(--link)',
          soft: 'var(--pettrace-coral-100)',
          deep: 'var(--pettrace-coral-600)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          fg: 'var(--secondary-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          fg: 'var(--accent-foreground)',
          soft: 'var(--pettrace-mint-50)',
        },
        honey: {
          DEFAULT: 'var(--warning)',
          soft: 'var(--pettrace-honey-50)',
        },
        success: 'var(--success)',
        warning: 'var(--warning)',
        error: {
          DEFAULT: 'var(--error)',
          container: 'var(--error-container)',
        },
        coral: {
          50: 'var(--pettrace-coral-50)',
          100: 'var(--pettrace-coral-100)',
          200: 'var(--pettrace-coral-200)',
          300: 'var(--pettrace-coral-300)',
          400: 'var(--pettrace-coral-400)',
          500: 'var(--pettrace-coral-500)',
          600: 'var(--pettrace-coral-600)',
        },
        mint: {
          50: 'var(--pettrace-mint-50)',
          100: 'var(--pettrace-mint-100)',
        },
      },
      boxShadow: {
        'card': 'var(--shadow-1)',
        'soft': 'var(--shadow-1)',
        'pop': 'var(--shadow-2)',
        'float': 'var(--shadow-3)',
        'primary-btn': '0 2px 8px rgba(247,107,122,0.25)',
      },
      fontFamily: {
        sans: ['var(--font-body)', '"PingFang SC"', '"Hiragino Sans GB"', '"Helvetica Neue"', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)'],
        heading: ['var(--font-heading)'],
        body: ['var(--font-body)'],
        mono: ['var(--font-mono)'],
      },
      keyframes: {
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'fade-up': { '0%': { opacity: '0', transform: 'translateY(8px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'pop-in': { '0%': { opacity: '0', transform: 'scale(0.92)' }, '60%': { opacity: '1', transform: 'scale(1.02)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        'bubble-in': { '0%': { opacity: '0', transform: 'translateY(6px) scale(0.96)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'shimmer': { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'marker-pulse': { '0%': { opacity: '0.8', transform: 'scale(0.6)' }, '100%': { opacity: '0', transform: 'scale(1.8)' } },
      },
      animation: {
        'fade-in': 'fade-in 220ms ease-out',
        'fade-up': 'fade-up 260ms ease-out',
        'pop-in': 'pop-in 320ms cubic-bezier(0.22, 1, 0.36, 1)',
        'bubble-in': 'bubble-in 240ms ease-out',
        'shimmer': 'shimmer 1.6s linear infinite',
        'marker-pulse': 'marker-pulse 2s ease-out infinite',
      },
    },
    plugins: [],
  }
}
